[package]
authors = ["Robert Hurst <rhurst@e-xact.com>"]
description = "Unison is a easy to use config loader which can collect configuration from flags, environment variables, and configuration files."
documentation = "https://docs.rs/unison"
homepage = "https://github.com/RobertWHurst/Unison"
license = "MIT"
name = "unison"
repository = "https://github.com/RobertWHurst/Unison"
version = "0.3.1"

[dependencies]
seckey = "0.6.1"
serde = "1.0.19"
serde_json = "1.0.5"
serde_yaml = "0.7.1"
toml = "0.4.5"
